name: Build and Push Docker Image

on:
  push:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: | python -m pip install --upgrade pip
      run: | pip install pytest

    - name: Run tests
      run: pytest test_app.py

    - name: Build Docker Iamge
      run: docker build -t aashishsharma5555/python-cicd-app .

    - name: Log in to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Iamge
      run: docker push aashishsharma5555/python-cicd-app
